# Generated by Django 4.0.6 on 2022-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me',
            name='education',
        ),
        migrations.AddField(
            model_name='me',
            name='education',
            field=models.ManyToManyField(to='base.education'),
        ),
        migrations.RemoveField(
            model_name='me',
            name='skills',
        ),
        migrations.AddField(
            model_name='me',
            name='skills',
            field=models.ManyToManyField(to='base.skills'),
        ),
        migrations.RemoveField(
            model_name='me',
            name='social_media',
        ),
        migrations.AddField(
            model_name='me',
            name='social_media',
            field=models.ManyToManyField(to='base.socialmedia'),
        ),
        migrations.RemoveField(
            model_name='me',
            name='tagline',
        ),
        migrations.AddField(
            model_name='me',
            name='tagline',
            field=models.ManyToManyField(to='base.taglines'),
        ),
    ]
