# Generated by Django 4.0.6 on 2022-07-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_me_education_me_education_remove_me_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
