# Generated by Django 4.0.6 on 2022-07-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_socialmedia_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='title',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='twitter',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='social_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='social_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
