# Generated by Django 4.0.6 on 2022-07-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me',
            name='tagline',
        ),
        migrations.AddField(
            model_name='me',
            name='tagline',
            field=models.JSONField(null=True),
        ),
    ]
