# Generated by Django 4.0.6 on 2022-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_about_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='level_prcentage',
        ),
        migrations.AddField(
            model_name='skills',
            name='prcentage',
            field=models.CharField(default=90, max_length=1),
            preserve_default=False,
        ),
    ]
