# Generated by Django 4.0.6 on 2022-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_skills_level_prcentage_skills_prcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='prcentage',
            field=models.CharField(max_length=2),
        ),
    ]
