# Generated by Django 4.0.6 on 2022-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_responsibility_experience_education_achivements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='achivements',
        ),
        migrations.AddField(
            model_name='education',
            name='achivements',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='experience',
            name='responsibility',
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibility',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
    ]
