# Generated by Django 4.0.6 on 2022-07-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_education_achivements_education_achivements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsibility',
        ),
    ]
