# Generated by Django 4.0.6 on 2022-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_responsibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('more', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='me',
            name='services',
            field=models.ManyToManyField(to='base.services'),
        ),
    ]
