# Generated by Django 4.0.6 on 2022-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_services_me_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon_class',
            field=models.CharField(default='bx', max_length=30),
            preserve_default=False,
        ),
    ]
