# Generated by Django 4.0.6 on 2022-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='social_icon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
